### ISSUE TITLE
Auto Profile Switching - Feature Request

### ISSUE THREAD

**Issue by lenuswalker** [JamesCJ60/AMD-APU-Tuning-Utility-Extreme#2]
Hey,

Not sure how to do a feature request on this project but I'd like to suggest a feature to have auto profile switching for a battery profile and plugged in profile. Maybe also some way to toggle profiles with a hotkey or some cli interface to your utility whereby I can use some script to change profiles based on different conditions. 

Let me know if you need any clarity on this. Love your project.

**Comment by JamesCJ60** [comment]
Hi, thanks for the feedback its greatly appreciated. I am currently looking into many different things regarding preset switching including using hotkeys/xinput to change them while in games.

**Comment by JamesCJ60** [comment]
I'll close this for the time being. If you have any further requests I've now opened the discussions section.
